# Generated by Django 4.2.2 on 2023-06-21 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='user_default.webp', upload_to='avatar/')),
                ('phone', models.IntegerField(blank=True, default=False)),
                ('gander', models.CharField(blank=True, max_length=40)),
                ('country', models.CharField(blank=True, max_length=40)),
                ('bio', models.TextField(blank=True, max_length=300)),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('verificated', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
