# Generated by Django 4.2.2 on 2023-06-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_subscription_remove_video_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='episode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
