# Generated by Django 4.1.9 on 2023-06-24 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_movie_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='season',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.serie'),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='category',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='category',
        ),
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='movie_category', to='video.category'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='play_list_category', to='video.category'),
        ),
        migrations.AddField(
            model_name='serie',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='serie_category', to='video.category'),
        ),
    ]
