# Generated by Django 4.1.9 on 2023-06-25 10:46

from django.db import migrations, models
import video.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_comment_movie_movie_is_last_serie_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=video.models.filename, verbose_name='تحميل الفيديو '),
        ),
    ]
