# Generated by Django 4.1.9 on 2023-06-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_video_url_alter_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='رابط الفيديو'),
        ),
    ]
