# Generated by Django 4.1.9 on 2023-06-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_alter_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='quality',
            field=models.CharField(max_length=100, verbose_name=' الجودة'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='رابط الفيديو '),
        ),
    ]
