# Generated by Django 4.1.9 on 2023-06-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_alter_video_quality_alter_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='scraping_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
