# Generated by Django 4.1.9 on 2023-07-23 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0011_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='play_list_serie', to='video.serie', verbose_name='تحديد المسلسل'),
        ),
    ]
